// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAI7BYMDcznlMf-nT1eR6pniHeft7XcUw',
    appId: '1:140593780245:android:cd4eb814d212aff8fba01c',
    messagingSenderId: '140593780245',
    projectId: 'timekeeper-22949',
    databaseURL: 'https://timekeeper-22949-default-rtdb.firebaseio.com',
    storageBucket: 'timekeeper-22949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6xkd1pfyRPrBe-_qPk9wSRyVj8PR97nA',
    appId: '1:140593780245:ios:bef2e031be5915eafba01c',
    messagingSenderId: '140593780245',
    projectId: 'timekeeper-22949',
    databaseURL: 'https://timekeeper-22949-default-rtdb.firebaseio.com',
    storageBucket: 'timekeeper-22949.appspot.com',
    iosClientId: '140593780245-noi31bgiqfq18f5vjv21v53qi938nif8.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeKeeper',
  );
}
